import {
  Smartphone,
  Shirt,
  BookOpen,
  ChefHat,
  Sofa,
  Dumbbell,
  Gamepad2,
  Wrench,
  FileText,
  Sparkles,
  Pill,
  Apple,
  Package,
  Heart,
  Footprints,
  Briefcase,
  Refrigerator,
  Cable,
  Pen,
  Flower2,
  Palette,
  Gem,
  Music,
  Camera,
  Car,
  Baby,
  Dog,
  Tent,
} from 'lucide-react-native';
import type { LucideIcon } from 'lucide-react-native';
import { ItemCategory } from '../types';

export const categoryIcons: Record<string, LucideIcon> = {
  electronics: Smartphone,
  clothing: Shirt,
  books: BookOpen,
  kitchen: ChefHat,
  furniture: Sofa,
  sports: Dumbbell,
  toys: Gamepad2,
  tools: Wrench,
  documents: FileText,
  cosmetics: Sparkles,
  medicine: Pill,
  food: Apple,
  accessories: Heart,
  shoes: Footprints,
  bags: Briefcase,
  homeAppliances: Refrigerator,
  digitalAccessories: Cable,
  stationery: Pen,
  plants: Flower2,
  art: Palette,
  collectibles: Gem,
  musicalInstruments: Music,
  cameras: Camera,
  automotive: Car,
  baby: Baby,
  petSupplies: Dog,
  outdoor: Tent,
  other: Package,
};

export const getCategoryIcon = (category: string): LucideIcon => {
  return categoryIcons[category] || Package;
};

// 预设分类列表（从 categoryIcons 派生，保证单一数据源）
export const PRESET_CATEGORIES: ItemCategory[] = Object.keys(categoryIcons) as ItemCategory[];

// 分类默认颜色映射（用于饼图等可视化）
export const CATEGORY_COLORS: Record<string, string> = {
  electronics: '#C8956D',
  clothing: '#6B7F4E',
  books: '#5C8A7A',
  kitchen: '#A07448',
  furniture: '#8B7355',
  sports: '#7BA05B',
  toys: '#E8A87C',
  tools: '#85B8CB',
  documents: '#A9A9A9',
  cosmetics: '#D4A5A5',
  medicine: '#B8D4E3',
  food: '#F4D03F',
  accessories: '#E8B4B8',
  shoes: '#A8D8EA',
  bags: '#D4A373',
  homeAppliances: '#95B8D1',
  digitalAccessories: '#B8B8D1',
  stationery: '#F0E68C',
  plants: '#90C695',
  art: '#DDA0DD',
  collectibles: '#FFD700',
  musicalInstruments: '#8B4513',
  cameras: '#2F4F4F',
  automotive: '#4682B4',
  baby: '#FFB6C1',
  petSupplies: '#8FBC8F',
  outdoor: '#20B2AA',
  other: '#7A7A7A',
};
